services:
  unikprojekt.api:
    image: ${DOCKER_REGISTRY-}unikprojektapi
    build:
      context: ./UnikProjekt.Api
      dockerfile: UnikProjekt.Api/Dockerfile
  
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: UnikProjekt-mssql