version: '3.4'

networks:
    myAppNetwork:

services:
  unikprojekt.mssql:
    container_name: "UnikSqlServerContainer"
    image: mcr.microsoft.com/mssql/server:latest
    ports:
        - "11433:1433"
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=myStong_Password123# 

  unikprojekt.api:
    # environment:
      # - ASPNETCORE_ENVIRONMENT=Development
    #   - ASPNETCORE_HTTP_PORTS=8080
    #   - ASPNETCORE_HTTPS_PORTS=8081

    container_name: "UnikApiContainer"
    image: ${DOCKER_REGISTRY-}unikprojekt.api
    ports:
      - "8001:80"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    build:
          context: .
          dockerfile: unikprojekt.api/Dockerfile
    depends_on:
          - unikprojekt.mssql

  webhousingassociation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      # - "8080"
      # - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
