services:
  unikprojekt.api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      # ASPNETCORE_HTTP_PORTS: "8080"
      # ASPNETCORE_HTTPS_PORTS: "8081"
      ASPNETCORE_URLS: "http://+:80"  
    ports:
      - "8080:80"
      - "8081:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      mssql:
        condition: service_healthy
  
  mssql:
    volumes:
        - ./.containers/database:/var/opt/mssql/data
    user: root
    ports:
      - "11433:1433"
    environment:
      MSSQL_SA_PASSWORD: "SqlPassword#1234"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PSqlPassword#1234", "-Q", "select 1"]
      interval: 1s
      retries: 20